alias: Lock the door
id: 4a161a05-5899-4b64-a863-da3f57f38695
trigger:
  platform: state
  entity_id: binary_sensor.people_home
  from: 'on'
  to: 'off'
action:
- service: switch.turn_on
  entity_id: switch.garageslot
- service: notify.telebot
  data:
    message: Garagedeur op slot gedaan