alias: Timerstop Hal
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.timerhal
action:
  - service: timer.cancel
    data:
      entity_id: timer.timerhal
  - service: light.turn_off
    entity_id: light.hal_light
  - service: light.turn_off
    entity_id: light.wled32