alias: Slapen
trigger:
  - platform: template
    value_template: >-
      {{
        states('input_datetime.house_silent_hours_start')
        ==
        states('sensor.time')+":00"
      }}
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
action:
- service: homeassistant.turn_off
  entity_id: group.woonkamer
- service: climate.set_temperature
  data:
    entity_id: climate.nefit_easy
    temperature: 18