esphome:
  name: esp01led
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Pjotr24"
  password: "rapidteapot022"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01Led Fallback Hotspot"
    password: "9pM4KVrEakY6"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO2
    num_leds: 60
    rgb_order: BRG
    name: "FastLED WS2811 Light"
    
  