esphome:
  name: tuya2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tuya2 Fallback Hotspot"
    password: "NslZyKr9vCJC"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Tuya2 Button"
    on_press:
      - switch.toggle: relay

      
switch:
  - platform: gpio
    name: "Slaapkamer"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes