esphome:
  name: vloerlamp
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Web server
web_server:
  port: 80  
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Vloerlamp Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "vloerlamp"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes