esphome:
  name: vvbeneden
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw

  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "vvbeneden Fallback Hotspot"
    password: "NslZyKr9vCJC"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret esphome_ota_password
# Enable Web server
web_server:
  port: 80  
  

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "vvbeneden Button"
    on_press:
      - switch.toggle: relay

      
switch:
  - platform: gpio
    name: "vloer_beneden"
    pin: GPIO12
    id: relay

